lunar-linux/lunar

- plugins/check-ldd.plugin
It didn't ignore /usr/share/games/ before.
> lddcheck should ignore files in /usr/share/

- libs/build.lunar
testing by default. If someone wants it they can always do -DBUILD_TESTING=1.
This won't catch all builds that use cmake, some use slightly different
verbiage to enable/disable the building of testing. But from what I have seen
it will catch most.
Like the -DSYSCONF_INSTALL_DIR switch, if a given cmake build does not recognize
the switch it will throw a harmless warning.
> build.lunar: Adding another D switch to default_cmake_config disabling

- libs/messages.lunar
1. There's no reason for the restriction to some specific TERM. All terminals
I know or tested either support the sequence or ignore it without printing it
to the console (including linux terminal)
2. use escape sequences instead of cryptic bytes
3. no need for a local variable
4. strip leading/trailing whitespace. This simply doesn't belong there.
> Simplify xterm title message code

- etc/config
The FTP server at ftp://ftp.kde.org/ doesn't even exist any more.
> /etc/lunar/config: Fix KDE_URL.

- libs/modules.lunar
Modules with only a DETAILS.$PLATFORM file will now be properly included
in the $MODULE_INDEX. Listing and finding sections has also been fixed
to include modules with only a DETAILS.$PLATFORM file available.
> Properly handle modules with only a DETAILS.$PLATFORM

- libs/build.lunar
This lets you add a line saying "TYPE=perl" or "TYPE=python2" or
"TYPE=cmake" to a module's DETAILS file to save on having to write
a BUILD script that just has "default_cmake_build" in it.
> Added support for module types.

- libs/build.lunar
file(6M) changes the message from "shared object" to "pie
executable" starting with release 5.33, for some reason.
> build.lunar: Added more pie to it.

- etc/config
- libs/sources.lunar
This can make builds go much faster if you have lots of RAM.
The default is "off" though because maybe you're not that bold.
> Tmpfs build: add an option to build modules in a tmpfs instead of on disk

- prog/lin
`lin` was exiting after installing the very first dependency. This seems
to fix that, and it's the smallest change I can envision to sort it out.
> Fix the dependency queue: This is the smallest change I found that could fix this.

- libs/modules.lunar
The whole blocked is wrapped in ( ), running in a subshell.
continue does not work for the for outside.
It's not needed anyway.
> remove broken continue

- menu/alias.menu
- menu/download.menu
- menu/integrity.menu
- menu/license.menu
- menu/mirrors.menu
Basically a code cleanup without changing any functionality.
The "shellcheck" utility had many things to say about our code, including the use of outdated constructs like using backticks instead of $() to do output substitution and quoting variables when their values were being used.  I also cleaned up trailing whitespaces and empty lines, and made the indentation more consistent.
> Shellcheck suggestions: menus

- prog/lvu
Bash has a ?: syntax which can be applied during parameter
expansion. shfmt, which contains a static analyser, identified
this bit of code as being something which could potentially
confuse the parser into thinking it's part of a ternary-operator
sequence.
So I just moved the key, with its colon in it, to a string variable
and removed all potential for confusion.
> fix-add-broken-depends: Ensure that it sees a string as a string

- libs/build.lunar
Use the realpath command instead.
> build.lunar: Don't parse the output of ls!

- prog/lvu
Previously, `lvu depends` would grep through /var/state/lunar/depends,
once for every dependency that it came across, with a potential
combinatorial explosion for something which lots and lots of stuff
depends on (like openssl, or perl).
This gets rid of the invocations of grep, in favor of doing everything
within the same process.  It loads up an associative array with the
relevant contents of /var/state/lunar/depends, and does all of its
operations in RAM instead of having to go through the Lunar depends
state file multiple times (I tried `lvu depends perl` in strace, and it
exec'ed /usr/bin/grep over 14,000 times!).
> lvu depends: Significantly speed things up

- libs/build.lunar
Without this, it will happily uninstall the current version when the build breaks...
> add missing && in python default builds

- man/lvu.1
- prog/lvu
This missing functionality was bugging me for over 10 years I guess...
I got into a habit of doing `tail -f /var/log/lunar/activity` instead,
but having the argument is definitely nicer.
Also I updated a bit of the docs which did not mention the optional module yet.
> add `lvu activity -f`

- libs/view.lunar
at least when it's not compressed.
This allows for file-based pager operations such as <shift>f in less.
> view_file: let the pager handle reading the file

- libs/moonbase.lunar
- prog/lrm
Possibly a matter of taste.
In case anyone objects, maybe we can make it optional?
My concrete use-case is a server system that automatically fetches the moonbase every few hours to notify me about important updates.
Of course that just adds a lot of useless entries in the activity log.
> do not log updating the moonbase

- libs/depends.lunar
Unfortunately tsort doesn't have enough data to figure out exactly which
module's optional dependencies caused the dependency loop, so sorting
that out is still something for the future.
But at least try to warn people of dependency loops before they waste
their time watching stuff compile which is never going to work.
> depends.lunar: Add code to warn about dependency loops.

- libs/depends.lunar
First of all, user "error_message" so that the error messages go to
standard error (duh) instead of polluting the input of whatever's
trying to call it.
Second of all, if standard out is a terminal, then ask questions. If
not, just soldier on. As the comment says, this is probably not the
ideal way to proceed.
> files.lunar: Halfway fix for the loop detector.

- libs/plugins.lunar
Check to make sure that $PPID is actually a `lin` before telling it to
update its own plugins.  It might be an `lsh` and the USR1 might only
end up confusing things.
Note that this is only a suggestion. There may well be a much better
way to handle this.
> plugins.lunar: Don't always send USR1 to $PPID

- libs/depends.lunar
This should fix `sort_by_dependency` which has mirrored the input as a return value for some time.
$DEPENDS_CACHE only contains an overview of all dependencies in moonbase, the "on" status does not exist in that file. $DEPENDS_STATUS does have that though, and it should be safe to use at this stage. `rework_module` is always called first to update $DEPENDS_STATUS before calling `sort_by_dependency`.
> fix: use depends status file to determine required deps

- libs/build.lunar
This is a fix about tar failing to extract if /usr/lib64 is a symlink, which is the case with default installations of Lunar.
> build.lunar: install libraries in correct path, lib64 to lib
